on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/ping-home-app.yml"
      - "packages/ping-home/app/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: google-github-actions/auth@v3
        id: auth
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.GOOGLE_CLOUD_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ env.GOOGLE_GHA_CREDS_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: packages/ping-home/app
          push: true
          tags: ${{ vars.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/lan-checker-repo/lan-checker:${{ github.sha }}
      - uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: home-lan-checker
          region: ${{ vars.GOOGLE_CLOUD_REGION }}
          image: ${{ vars.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/lan-checker-repo/lan-checker:${{ github.sha }}
